name: md_assistant
description: Personal assistant

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.14+16

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  path_provider: ^2.0.15
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  flutter_localization: ^0.1.12
  window_manager: ^0.3.5
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.2.0
  google_sign_in: ^6.1.4
  googleapis: ^11.3.0
  firebase_core: ^2.15.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 600

