# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - run: |
        git worktree add -B gh-pages public origin/gh-pages
        git worktree remove public
        git worktree add -B gh-pages build/web origin/gh-pages
        git push origin gh-pages
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux
    - uses: actions/upload-artifact@v3
      with: 
        name: linux-build
        path: build/linux/x64/release/bundle/
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v3
      with:
        name: android-build  
        path: build/app/outputs/flutter-apk/app-release.apk
        
